service: kraft-envios-api-pnpm-11

provider:
  name: aws
  runtime: nodejs22.x
  stage: dev
  region: us-east-1
  logRetentionInDays: 1
  timeout: 45
  stackName: kraft-envios-api-test-pnpm
  apiName: kraft-envios-api-test-pnpm

package:
  patterns:
    - '.bundle/**'
    - '!src/**'
    - '!test/**'
    - '!emails/**'
    - '!dist/**'
    - '!node_modules/**'
    - '!coverage/**'
    - '!docs/**'

functions:
  api:
    handler: .bundle/index.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

plugins:
  - serverless-offline